[phases.setup]
nixPkgs = ["nodejs", "python39", "pip"]

[phases.install]
cmds = [
    "pip install -r requirements_backend.txt",
    "cd frontend && npm ci && npm run build"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "uvicorn backend_server:app --host 0.0.0.0 --port $PORT"