version = 0.1

[default]
[default.global.parameters]
stack_name = "multi-agent-research-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "GroqApiKey=YOUR_GROQ_API_KEY_HERE"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
fail_on_empty_changeset = false
resolve_s3 = true
s3_prefix = "multi-agent-research-backend"
disable_rollback = true
image_repositories = []

[default.package.parameters]
s3_bucket = ""  # SAM will create a managed bucket

[default.sync.parameters]
watch = true